name: Reusable workflow example

on:
  workflow_call:
#     inputs:
#       config-path:
#         required: true
#         type: string
#     secrets:
#       token:
#         required: true

jobs:
  test-something:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
