name: Call a reusable workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: ./.github/workflows/action1.yml

  # call-workflow-passing-data:
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   uses: MonseGuzman/github-actions-practices/.github/workflows/workflow-B.yml@main
  #   with:
  #     config-path: .github/labeler.yml
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}
